### ISSUE TITLE
Executions hinting

### ISSUE THREAD

**Issue by Vyacheslav-Lapin** [ris58h/laconic-pom#2]
It'll be great to hint executions in plugin configurations like this:
<img width="961" alt="image" src="https://user-images.githubusercontent.com/930608/227897229-b26852c8-9a8c-42c1-9283-d278a817fd48.png">
format: {id}:{phase}:{goals/goal, maybe comma-separated if more then one}

**Comment by ris58h** [comment]
I don't know much about `executions` but it seems like checking the `id` property is enough to identify one from another. I mean, we shouldn't put every property in a folding description - only the most important ones.

Will `id` property be enough?
<img width="810" alt="Screenshot 2023-03-27 at 19 04 57" src="https://user-images.githubusercontent.com/511242/227999712-a7662bd7-2e3c-49e9-b6e1-a902e5cde604.png">

**Comment by lppedd** [comment]
@ris58h my 2c. When the ID is not present, use the specified goals as `goal-1, goal-2, goal-3`.
